version: "3.9"
services:
  server:
    ports:
      - "50051"
    build:
      context: .
      dockerfile: test.dockerfile
    environment:
      - DB_URL="jdbc://localhost:3306"
      - DB_USERNAME=test
      - DB_PASSWORD=test123
  
  database:
    image: "mariadb:latest"
    environment:
      - MARIADB_DATABASE=munchy
      - MARIADB_USER=test
      - MARIADB_PASSWORD=test123
      - MARIADB_ROOT_PASSWORD=test123
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro

    