version: "3.9"
services:
  server:
    ports:
      - "50051:50051"
    build:
      context: .
      dockerfile: test.dockerfile
    environment:
      - DB_URL=jdbc:mariadb://database:3306/munchy
      - DB_USERNAME=test
      - DB_PASSWORD=test123
  
  database:
    image: "mariadb:latest"
    environment:
      - MARIADB_DATABASE=munchy
      - MARIADB_USER=test
      - MARIADB_PASSWORD=test123
      - MARIADB_ROOT_PASSWORD=test123
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro

    